language: java

matrix:
  include:
    - os: linux
      dist: precise
      jdk: oraclejdk7
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: oraclejdk9
    - os: linux
      jdk: oraclejdk10
    - os: linux
      jdk: openjdk10

env:
    - TERM=dumb

script:
    - gradle assemble

branches:
    - master
    - 1.x
